# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('arrivalDate', models.DateTimeField(verbose_name='arrival date')),
            ],
        ),
    ]
